# Generated by Django 4.2.2 on 2023-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemyto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_gemyto',
            field=models.FloatField(default=0),
        ),
    ]
