# Generated by Django 4.2.2 on 2023-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
