# Generated by Django 4.2.2 on 2023-07-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_socialmedia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='played_game',
            field=models.BooleanField(default=False),
        ),
    ]
