# Generated by Django 4.2.2 on 2023-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GemytoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gemyto_info',
            },
        ),
    ]
