# Generated by Django 4.2.2 on 2023-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_news',
            },
        ),
        migrations.CreateModel(
            name='GemytoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gemyto_info',
                'ordering': ['created_at'],
            },
        ),
    ]
