# Generated by Django 4.1.7 on 2023-06-14 11:18

from django.db import migrations, models
import game_master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=game_master.models.game_master_avatar_directory_path)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'game master',
                'verbose_name_plural': 'game masters',
                'ordering': ['created_at'],
            },
        ),
    ]
