# Generated by Django 4.2.2 on 2023-06-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamemaster',
            table='game_master',
        ),
    ]
