# Generated by Django 4.2.2 on 2023-07-19 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_dailyplayedgame_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_master',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.game_picture_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), game.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='game',
            name='scores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_game', to='game.scores'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('action', 'action'), ('shooting', 'shooting'), ('quiz', 'quiz'), ('sport', 'sport'), ('puzzle', 'puzzle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_of_users_get_gemyto',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
