# Generated by Django 4.2.2 on 2023-07-07 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playedgame',
            options={'ordering': ['score'], 'verbose_name': 'played game', 'verbose_name_plural': 'played games'},
        ),
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.game_picture_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), game.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='num_of_like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='num_of_users_get_gemyto',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='playedgame',
            name='game_gemyto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playedgame',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_of_report',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='playedgame',
            table='played_game',
        ),
        migrations.CreateModel(
            name='DailyPlayedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(null=True)),
                ('state', models.PositiveIntegerField(choices=[(1, 'State 1'), (2, 'State 2'), (3, 'State 3'), (4, 'State 4')], default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_daily_players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' daily played game',
                'verbose_name_plural': 'daily played games',
                'db_table': 'daily_played_game',
                'ordering': ['score'],
            },
        ),
    ]
