# Generated by Django 4.2.2 on 2023-07-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_game_master_remove_scores_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_game', to='game.scores'),
        ),
    ]
